<h1 align="center" style="
           background:rgba(44, 39, 33, 0.5);
           color:rgba(141, 82, 15, 0.93);
           font-size:45px;
           padding:20px;
           border-radius:12px;">

  <span>
    <img src="https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg"
         width="65"
         style="vertical-align:middle;">
    <b> AWS Cloud Cost Optimization</b>
  </span>

</h1>

### <b>Dataset – Overview</b>

This project utilizes a **real-world AWS Cost and Usage Report (CUR) dataset** generated from my personal AWS account while working on various cloud-based projects and experiments. The billing data was collected directly from AWS Cost Explorer and Cost & Usage Reports, which provide detailed records of resource consumption and associated costs across AWS services.

To prepare the dataset for analysis, the original CUR data was preprocessed and cleaned by selecting the most relevant attributes related to cloud infrastructure, service usage, pricing, resource configurations, and organizational metadata. The resulting billing dataset contains **2,516 records (rows)** and **30 features (columns)**, making it suitable for cloud cost analysis and machine learning applications.

The dataset includes information such as AWS account details, services, regions, resource identifiers, instance specifications, usage quantities, billing costs, pricing models, operating systems, storage configurations, and resource tags. These attributes provide valuable insights into cloud resource consumption patterns and spending behavior.

The primary goal of this dataset is to support **AWS Cloud Cost Optimization** and **FinOps-driven decision making**. 
By integrating billing records with operational usage metrics, the dataset enables:

* **Cost Allocation and Spending Analysis**
* **Resource Utilization Monitoring**
* **Cloud Waste Detection**
* **Idle Resource Identification**
* **Infrastructure Rightsizing Recommendations**
* **Cost Anomaly Detection**
* **Cost Forecasting and Budget Planning**
* **Machine Learning-Based Cost Optimization**
* **Cloud Resource Efficiency Analysis**

### <b>🧑‍💼 Project Author</b>

***Author: Muhammad Usman***

***Data Science . AI/ML . DataEngineering Enthusiast***

***Date: May 2026***

<h2 style="text-align:center; 
           background:rgba(63, 56, 46, 0.5);
           color:rgb(232, 140, 35); 
           font-size:38px; 
           padding:15px;
           border-radius:12px;
           display: inline-block">
     <b> Importing Libraries</b>
</h2>

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

<h2 style="text-align:center; 
           background:rgba(63, 56, 46, 0.5);
           color:rgb(232, 140, 35); 
           font-size:38px; 
           padding:15px;
           border-radius:12px;
           display: inline-block">
     <b> Loading Dataset | Analyzing</b>
</h2>

In [3]:
data = pd.read_excel(r"../data\raw\Fintech_output_Usman.xlsx")
# data = pd.read_csv(r"../data/raw/real+synthetic_aws.csv")

* <b> Make the copy of original dataset into a new variable, to keep both cleaned and raw dataset separately

In [4]:
cleaned_data = data.copy()

* **show max columns**

In [5]:
pd.set_option('display.max_columns', None)

* <b> Display top 5 rows </b>

In [6]:
data.head(5)

,identity_line_item_id,identity_time_interval,bill_invoice_id,bill_invoicing_entity,bill_billing_entity,bill_bill_type,bill_payer_account_id,bill_billing_period_start_date,bill_billing_period_end_date,line_item_usage_account_id,line_item_line_item_type,line_item_usage_start_date,line_item_usage_end_date,line_item_product_code,line_item_usage_type,line_item_operation,line_item_availability_zone,line_item_resource_id,line_item_usage_amount,line_item_normalization_factor,line_item_normalized_usage_amount,line_item_currency_code,line_item_unblended_rate,line_item_unblended_cost,line_item_blended_rate,line_item_blended_cost,line_item_line_item_description,line_item_tax_type,line_item_legal_entity,product_product_name,product_availability,product_availability_zone,product_capacitystatus,product_classicnetworkingsupport,product_clock_speed,product_current_generation,product_database_engine,product_dedicated_ebs_throughput,product_dedicated_ebs_throughput_description,product_deployment_option,product_durability,product_ecu,product_engine_code,product_enhanced_networking_supported,product_fee_code,product_fee_description,product_from_location,product_from_location_type,product_from_region_code,product_gpu_memory,product_group,product_group_description,product_instance,product_instance_family,product_instance_family_category,product_instance_type,product_instance_type_family,product_intel_avx2_available,product_intel_avx_available,product_intel_turbo_available,product_license_model,product_location,product_location_type,product_logs_destination,product_marketoption,product_max_iopsvolume,product_max_throughputvolume,product_max_volume_size,product_memory,product_message_delivery_frequency,product_message_delivery_order,product_network_performance,product_normalization_size_factor,product_operating_system,product_operation,product_physical_processor,product_pre_installed_sw,product_processor_architecture,product_processor_features,product_product_family,product_queue_type,product_region,product_region_code,product_servicecode,product_servicename,product_sku,product_storage,product_storage_class,product_storage_media,product_tenancy,product_to_location,product_to_location_type,product_to_region_code,product_transfer_type,product_usagetype,product_vcpu,product_version,product_volume_api_name,product_volume_type,product_vpcnetworkingsupport,pricing_rate_code,pricing_rate_id,pricing_currency,pricing_public_on_demand_cost,pricing_public_on_demand_rate,pricing_term,pricing_unit,reservation_amortized_upfront_cost_for_usage,reservation_amortized_upfront_fee_for_billing_period,reservation_effective_cost,reservation_end_time,reservation_modification_status,reservation_normalized_units_per_reservation,reservation_number_of_reservations,reservation_recurring_fee_for_usage,reservation_start_time,reservation_subscription_id,reservation_total_reserved_normalized_units,reservation_total_reserved_units,reservation_units_per_reservation,reservation_unused_amortized_upfront_fee_for_billing_period,reservation_unused_normalized_unit_quantity,reservation_unused_quantity,reservation_unused_recurring_fee,reservation_upfront_value,savings_plan_total_commitment_to_date,savings_plan_savings_plan_a_r_n,savings_plan_savings_plan_rate,savings_plan_used_commitment,savings_plan_savings_plan_effective_cost,savings_plan_amortized_upfront_commitment_for_billing_period,savings_plan_recurring_commitment_for_billing_period,resource_tags_aws_created_by,resource_tags_user_name,resource_tags_user_environment,resource_tags_user_owner,resource_tags_user_project,resource_tags_user_team
0,co7xwzkxovgiruodsvd6xbsdcinwtaylvni3wz6a7lk7zj...,2026-04-01T00:00:00Z/2026-05-01T00:00:00Z,NaN,"Amazon Web Services, Inc.",AWS,Anniversary,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,195000000000,Tax,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,AmazonEC2,BoxUsage:t3.micro,RunInstances,NaN,NaN,1.0,0.0,0.0,USD,NaN,0.0,NaN,0.0,Tax for product code AmazonEC2 usage type BoxU...,VAT,"Amazon Web Services, Inc.",Amazon Elastic Compute Cloud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,qmgclm56i7mqwcslnlsuha2tqxyxngrih6z54ueaitcnk2...,2026-04-01T00:00:00Z/2026-05-01T00:00:00Z,NaN,"Amazon Web Services, Inc.",AWS,Anniversary,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,195000000000,Tax,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,AmazonEC2,CPUCredits:t3,T3CPUCredits,NaN,NaN,1.0,0.0,0.0,USD,NaN,0.0,NaN,0.0,Tax for product code AmazonEC2 usage type CPUC...,VAT,"Amazon Web Services, Inc.",Amazon Elastic Compute Cloud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,xbnbh44odu6n5wkg4ohrvrqft7iwsprmoai5ieipnx7n3p...,2026-04-01T00:00:00Z/2026-05-01T00:00:00Z,NaN,"Amazon Web Services, Inc.",AWS,Anniversary,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,195000000000,Tax,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,AmazonEC2,EBS:VolumeUsage.gp3,NaN,NaN,NaN,1.0,0.0,0.0,USD,NaN,0.0,NaN,0.0,Tax for product code AmazonEC2 usage type EBS:...,VAT,"Amazon Web Services, Inc.",Amazon Elastic Compute Cloud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,e35ffv23rdsyx3rzxui7spgs2k6kyw7q3mvrg3pxg57hor...,2026-04-01T00:00:00Z/2026-05-01T00:00:00Z,NaN,"Amazon Web Services, Inc.",AWS,Anniversary,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,195000000000,Tax,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,AmazonRDS,Aurora:ServerlessV2Usage,CreateDBInstance:0021,NaN,NaN,1.0,0.0,0.0,USD,NaN,0.0,NaN,0.0,Tax for product code AmazonRDS usage type Auro...,VAT,"Amazon Web Services, Inc.",Amazon Relational Database Service,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,k4n4lzsfy6yld5bx3spthvcor5co7qvj74unc4xtvn2ygh...,2026-04-01T00:00:00Z/2026-05-01T00:00:00Z,NaN,"Amazon Web Services, Inc.",AWS,Anniversary,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,195000000000,Tax,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,AmazonVPC,USE1-PublicIPv4:InUseAddress,NaN,NaN,NaN,1.0,0.0,0.0,USD,NaN,0.0,NaN,0.0,Tax for product code AmazonVPC usage type USE1...,VAT,"Amazon Web Services, Inc.",Amazon Virtual Private Cloud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

* <b> Display random no. of rows </b>

In [7]:
data.sample(2)

,identity_line_item_id,identity_time_interval,bill_invoice_id,bill_invoicing_entity,bill_billing_entity,bill_bill_type,bill_payer_account_id,bill_billing_period_start_date,bill_billing_period_end_date,line_item_usage_account_id,line_item_line_item_type,line_item_usage_start_date,line_item_usage_end_date,line_item_product_code,line_item_usage_type,line_item_operation,line_item_availability_zone,line_item_resource_id,line_item_usage_amount,line_item_normalization_factor,line_item_normalized_usage_amount,line_item_currency_code,line_item_unblended_rate,line_item_unblended_cost,line_item_blended_rate,line_item_blended_cost,line_item_line_item_description,line_item_tax_type,line_item_legal_entity,product_product_name,product_availability,product_availability_zone,product_capacitystatus,product_classicnetworkingsupport,product_clock_speed,product_current_generation,product_database_engine,product_dedicated_ebs_throughput,product_dedicated_ebs_throughput_description,product_deployment_option,product_durability,product_ecu,product_engine_code,product_enhanced_networking_supported,product_fee_code,product_fee_description,product_from_location,product_from_location_type,product_from_region_code,product_gpu_memory,product_group,product_group_description,product_instance,product_instance_family,product_instance_family_category,product_instance_type,product_instance_type_family,product_intel_avx2_available,product_intel_avx_available,product_intel_turbo_available,product_license_model,product_location,product_location_type,product_logs_destination,product_marketoption,product_max_iopsvolume,product_max_throughputvolume,product_max_volume_size,product_memory,product_message_delivery_frequency,product_message_delivery_order,product_network_performance,product_normalization_size_factor,product_operating_system,product_operation,product_physical_processor,product_pre_installed_sw,product_processor_architecture,product_processor_features,product_product_family,product_queue_type,product_region,product_region_code,product_servicecode,product_servicename,product_sku,product_storage,product_storage_class,product_storage_media,product_tenancy,product_to_location,product_to_location_type,product_to_region_code,product_transfer_type,product_usagetype,product_vcpu,product_version,product_volume_api_name,product_volume_type,product_vpcnetworkingsupport,pricing_rate_code,pricing_rate_id,pricing_currency,pricing_public_on_demand_cost,pricing_public_on_demand_rate,pricing_term,pricing_unit,reservation_amortized_upfront_cost_for_usage,reservation_amortized_upfront_fee_for_billing_period,reservation_effective_cost,reservation_end_time,reservation_modification_status,reservation_normalized_units_per_reservation,reservation_number_of_reservations,reservation_recurring_fee_for_usage,reservation_start_time,reservation_subscription_id,reservation_total_reserved_normalized_units,reservation_total_reserved_units,reservation_units_per_reservation,reservation_unused_amortized_upfront_fee_for_billing_period,reservation_unused_normalized_unit_quantity,reservation_unused_quantity,reservation_unused_recurring_fee,reservation_upfront_value,savings_plan_total_commitment_to_date,savings_plan_savings_plan_a_r_n,savings_plan_savings_plan_rate,savings_plan_used_commitment,savings_plan_savings_plan_effective_cost,savings_plan_amortized_upfront_commitment_for_billing_period,savings_plan_recurring_commitment_for_billing_period,resource_tags_aws_created_by,resource_tags_user_name,resource_tags_user_environment,resource_tags_user_owner,resource_tags_user_project,resource_tags_user_team
2399,d4q5ijwmjcarhmocxk4lvndszt3iet4xmzvkqkpiajfwxw...,2026-04-11T19:00:00Z/2026-04-11T20:00:00Z,NaN,"Amazon Web Services, Inc.",AWS,Anniversary,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,195000000000,Usage,2026-04-11 19:00:00+00:00,2026-04-11 20:00:00+00:00,AWSLambda,Request,Invoke,NaN,arn:aws:lambda:us-east-1:195216431976:function...,26.000000,0.0,0.0,USD,0.00,0.000000,0.00,0.000000,"AWS Lambda - Requests Free Tier - 1,000,000 Re...",NaN,"Amazon Web Services, Inc.",AWS Lambda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AWS-Lambda-Requests,Invocation call for a Lambda function,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US East (N. Virginia),AWS Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serverless,NaN,us-east-1,us-east-1,AWSLambda,AWS Lambda,GU2ZS9HVP6QTQ7KE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Request,NaN,NaN,NaN,NaN,NaN,GU2ZS9HVP6QTQ7KE.A429C66SYZ.6YS6EN2CT7,4.380000e+11,USD,0.000005,2.000000e-07,NaN,Requests,0,0,0,NaN,NaN,NaN,NaN,0,NaN,2.304825e+10,NaN,NaN,NaN,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1171,avhz2kikamdu7dsty4zs3aoefoi7xwjpnorqysu2b2arof...,2026-04-12T12:00:00Z/2026-04-12T13:00:00Z,NaN,"Amazon Web Services, Inc.",AWS,Anniversary,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,195000000000,Usage,2026-04-12 12:00:00+00:00,2026-04-12 13:00:00+00:00,AmazonEC2,EBS:VolumeUsage.gp3,CreateVolume-Gp3,NaN,vol-0843bd7e40442c416,0.022222,0.0,0.0,USD,0.08,0.001778,0.08,0.001778,$0.08 per GB-month of General Purpose (gp3) pr...,NaN,"Amazon Web Services, Inc.",Amazon Elastic Compute Cloud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US East (N. Virginia),AWS Region,NaN,NaN,80000.0,2000 MiB/s,64 TiB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Storage,NaN,us-east-1,us-east-1,AmazonEC2,Amazon Elastic Compute Cloud,JG3KUJMBRGHV3N8G,NaN,NaN,SSD-backed,NaN,NaN,NaN,NaN,NaN,EBS:VolumeUsage.gp3,NaN,NaN,gp3,General Purpose,NaN,JG3KUJMBRGHV3N8G.JRTCKXETXF.6YS6EN2CT7,4.420000e+11,USD,0.001778,8.000000e-02,OnDemand,GB-Mo,0,0,0,NaN,NaN,NaN,NaN,0,NaN,2.304825e+10,NaN,NaN,NaN,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

* <b>To get concise summary of whole dataset, including datatypes

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2516 entries, 0 to 2515
Columns: 138 entries, identity_line_item_id to resource_tags_user_team
dtypes: float64(33), int64(17), str(88)
memory usage: 2.6 MB

<h2 style="text-align:center; 
           background:rgba(63, 56, 46, 0.5);
           color:rgb(232, 140, 35); 
           font-size:38px; 
           padding:15px;
           border-radius:12px;
           display: inline-block">
     <b> Feature Transformation | Selection | Analyzing</b>
</h2>

* This is the process where we change `columns names`, `data types`, and `values` to make the data more suitable for analysis and modeling, 

it includes operations like `renaming columns`, `converting data types`, `handling missing values`, and `creating new features`.

In [9]:
# Rename columns
cleaned_data = data.rename(columns={

# Identity & Billing
"identity_line_item_id":"record_id",
"identity_time_interval":"time_interval",
"bill_invoice_id":"invoice_id",
"bill_invoicing_entity":"invoice_provider",
"bill_billing_entity":"billing_provider",
"bill_bill_type":"bill_type",
"bill_payer_account_id":"payer_account",
"bill_billing_period_start_date":"billing_start_date",
"bill_billing_period_end_date":"billing_end_date",

# Usage Information
"line_item_usage_account_id":"account_id",
"line_item_line_item_type":"usage_category",
"line_item_usage_start_date":"usage_start",
"line_item_usage_end_date":"usage_end",
"line_item_product_code":"service_code",
"line_item_usage_type":"usage_type",
"line_item_operation":"operation",
"line_item_availability_zone":"availability_zone",
"line_item_resource_id":"resource_id",
"line_item_usage_amount":"usage_amount",
"line_item_normalization_factor":"normalization_factor",
"line_item_normalized_usage_amount":"normalized_usage",
"line_item_currency_code":"currency",
"line_item_unblended_rate":"cost_rate",
"line_item_unblended_cost":"cost",
"line_item_blended_rate":"blended_rate",
"line_item_blended_cost":"blended_cost",
"line_item_line_item_description":"description",
"line_item_tax_type":"tax_type",
"line_item_legal_entity":"legal_entity",

# Product Information
"product_product_name":"service_name",
"product_availability":"availability",
"product_availability_zone":"product_az",
"product_capacitystatus":"capacity_status",
"product_classicnetworkingsupport":"classic_networking",
"product_clock_speed":"cpu_speed",
"product_current_generation":"current_generation",
"product_database_engine":"database_engine",
"product_dedicated_ebs_throughput":"ebs_throughput",
"product_dedicated_ebs_throughput_description":"ebs_throughput_desc",
"product_deployment_option":"deployment_option",
"product_durability":"durability",
"product_ecu":"ecu",
"product_engine_code":"engine_code",
"product_enhanced_networking_supported":"enhanced_networking",
"product_fee_code":"fee_code",
"product_fee_description":"fee_description",
"product_from_location":"source_location",
"product_from_location_type":"source_location_type",
"product_from_region_code":"source_region",
"product_gpu_memory":"gpu_memory",
"product_group":"resource_group",
"product_group_description":"group_description",
"product_instance":"instance",
"product_instance_family":"instance_family",
"product_instance_family_category":"instance_category",
"product_instance_type":"instance_type",
"product_instance_type_family":"instance_family_type",
"product_intel_avx2_available":"intel_avx2",
"product_intel_avx_available":"intel_avx",
"product_intel_turbo_available":"intel_turbo",
"product_license_model":"license_model",
"product_location":"location",
"product_location_type":"location_type",
"product_logs_destination":"log_destination",
"product_marketoption":"market_option",
"product_max_iopsvolume":"max_iops",
"product_max_throughputvolume":"max_throughput",
"product_max_volume_size":"max_volume",
"product_memory":"memory",
"product_message_delivery_frequency":"delivery_frequency",
"product_message_delivery_order":"delivery_order",
"product_network_performance":"network_performance",
"product_normalization_size_factor":"size_factor",
"product_operating_system":"operating_system",
"product_operation":"product_operation",
"product_physical_processor":"processor",
"product_pre_installed_sw":"preinstalled_software",
"product_processor_architecture":"architecture",
"product_processor_features":"processor_features",
"product_product_family":"product_family",
"product_queue_type":"queue_type",
"product_region":"region",
"product_region_code":"region_code",
"product_servicecode":"service_code_product",
"product_servicename":"service",
"product_sku":"sku",
"product_storage":"storage",
"product_storage_class":"storage_class",
"product_storage_media":"storage_media",
"product_tenancy":"tenancy",
"product_to_location":"destination_location",
"product_to_location_type":"destination_location_type",
"product_to_region_code":"destination_region",
"product_transfer_type":"transfer_type",
"product_usagetype":"usage_category_product",
"product_vcpu":"vcpu",
"product_version":"version",
"product_volume_api_name":"volume_api",
"product_volume_type":"volume_type",
"product_vpcnetworkingsupport":"vpc_networking",

# Pricing
"pricing_rate_code":"rate_code",
"pricing_rate_id":"rate_id",
"pricing_currency":"pricing_currency",
"pricing_public_on_demand_cost":"ondemand_cost",
"pricing_public_on_demand_rate":"ondemand_rate",
"pricing_term":"pricing_term",
"pricing_unit":"pricing_unit",

# Reservation
"reservation_amortized_upfront_cost_for_usage":"reserved_upfront_cost",
"reservation_amortized_upfront_fee_for_billing_period":"reserved_fee",
"reservation_effective_cost":"reserved_effective_cost",
"reservation_end_time":"reservation_end",
"reservation_modification_status":"reservation_status",
"reservation_normalized_units_per_reservation":"normalized_units",
"reservation_number_of_reservations":"reservation_count",
"reservation_recurring_fee_for_usage":"recurring_fee",
"reservation_start_time":"reservation_start",
"reservation_subscription_id":"subscription_id",
"reservation_total_reserved_normalized_units":"total_reserved_normalized",
"reservation_total_reserved_units":"total_reserved_units",
"reservation_units_per_reservation":"units_per_reservation",
"reservation_unused_amortized_upfront_fee_for_billing_period":"unused_reserved_fee",
"reservation_unused_normalized_unit_quantity":"unused_normalized_units",
"reservation_unused_quantity":"unused_quantity",
"reservation_unused_recurring_fee":"unused_fee",
"reservation_upfront_value":"upfront_value",

# Savings Plans
"savings_plan_total_commitment_to_date":"total_commitment",
"savings_plan_savings_plan_a_r_n":"savingsplan_arn",
"savings_plan_savings_plan_rate":"savingsplan_rate",
"savings_plan_used_commitment":"used_commitment",
"savings_plan_savings_plan_effective_cost":"effective_savings_cost",
"savings_plan_amortized_upfront_commitment_for_billing_period":"upfront_commitment",
"savings_plan_recurring_commitment_for_billing_period":"recurring_commitment",

# Tags
"resource_tags_aws_created_by":"created_by",
"resource_tags_user_name":"resource_name",
"resource_tags_user_environment":"environment",
"resource_tags_user_owner":"owner",
"resource_tags_user_project":"project",
"resource_tags_user_team":"team"

})

In [10]:
data.columns

Index(['identity_line_item_id', 'identity_time_interval', 'bill_invoice_id',
       'bill_invoicing_entity', 'bill_billing_entity', 'bill_bill_type',
       'bill_payer_account_id', 'bill_billing_period_start_date',
       'bill_billing_period_end_date', 'line_item_usage_account_id',
       ...
       'savings_plan_used_commitment',
       'savings_plan_savings_plan_effective_cost',
       'savings_plan_amortized_upfront_commitment_for_billing_period',
       'savings_plan_recurring_commitment_for_billing_period',
       'resource_tags_aws_created_by', 'resource_tags_user_name',
       'resource_tags_user_environment', 'resource_tags_user_owner',
       'resource_tags_user_project', 'resource_tags_user_team'],
      dtype='str', length=138)

In [11]:
cleaned_data.columns

Index(['record_id', 'time_interval', 'invoice_id', 'invoice_provider',
       'billing_provider', 'bill_type', 'payer_account', 'billing_start_date',
       'billing_end_date', 'account_id',
       ...
       'used_commitment', 'effective_savings_cost', 'upfront_commitment',
       'recurring_commitment', 'created_by', 'resource_name', 'environment',
       'owner', 'project', 'team'],
      dtype='str', length=138)

<h2 style="text-align:center; 
           /* background:rgba(63, 56, 46, 0.5); */
           color:rgb(232, 140, 35); 
           font-size:35px; 
           padding:15px;
           border-radius:12px;
           display: inline-block">
     <b> Feature  Selection</b>
</h2>

In [12]:
important_columns = [
    
'account_id',
'usage_start',
'usage_end',
'service',
'service_code',
'resource_id',
'instance_type',
'instance_family',
'region',
# 'availability_zone',
'usage_type',
'usage_amount',
'normalized_usage',
'operation',
'cost',
'cost_rate',
'currency',
'pricing_term',
'operating_system',
'vcpu',
'memory',
'network_performance',
'storage',
'storage_class',
'volume_type',
'processor',
'architecture',
'created_by',
'environment',
'project',
'team'
# 'owner'

]

In [13]:
cleaned_data = cleaned_data[important_columns]

In [14]:
# show all selected cleaned columns
cleaned_data.columns

Index(['account_id', 'usage_start', 'usage_end', 'service', 'service_code',
       'resource_id', 'instance_type', 'instance_family', 'region',
       'usage_type', 'usage_amount', 'normalized_usage', 'operation', 'cost',
       'cost_rate', 'currency', 'pricing_term', 'operating_system', 'vcpu',
       'memory', 'network_performance', 'storage', 'storage_class',
       'volume_type', 'processor', 'architecture', 'created_by', 'environment',
       'project', 'team'],
      dtype='str')

In [15]:
cleaned_data

,account_id,usage_start,usage_end,service,service_code,resource_id,instance_type,instance_family,region,usage_type,usage_amount,normalized_usage,operation,cost,cost_rate,currency,pricing_term,operating_system,vcpu,memory,network_performance,storage,storage_class,volume_type,processor,architecture,created_by,environment,project,team
0,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,NaN,AmazonEC2,NaN,NaN,NaN,NaN,BoxUsage:t3.micro,1.000000,0.000000,RunInstances,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,NaN,AmazonEC2,NaN,NaN,NaN,NaN,CPUCredits:t3,1.000000,0.000000,T3CPUCredits,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,NaN,AmazonEC2,NaN,NaN,NaN,NaN,EBS:VolumeUsage.gp3,1.000000,0.000000,NaN,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,NaN,AmazonRDS,NaN,NaN,NaN,NaN,Aurora:ServerlessV2Usage,1.000000,0.000000,CreateDBInstance:0021,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,NaN,AmazonVPC,NaN,NaN,NaN,NaN,USE1-PublicIPv4:InUseAddress,1.000000,0.000000,NaN,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,195000000000,2026-04-11 19:00:00+00:00,2026-04-11 20:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0d969006fcc3aa583,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.128889,0.064445,RunInstances,0.001340,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,NaN,NaN,NaN,NaN
2512,195000000000,2026-04-12 19:00:00+00:00,2026-04-12 20:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0df68563b3c5fa86f,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.575278,0.287639,RunInstances,0.005983,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,NaN,NaN,NaN,NaN
2513,195000000000,2026-04-12 20:00:00+00:00,2026-04-12 21:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0df68563b3c5fa86f,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.468889,0.234445,RunInstances,0.004876,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,NaN,NaN,NaN,NaN
2514,195000000000,2026-04-14 08:00:00+00:00,2026-04-14 09:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0a5b9c01d1bbecc0b,t3.micro,General purpose,us-east-1,EBSOptimized:t3.micro,0.690556,0.345278,Hourly,0.000000,0.0000,USD,OnDemand,NaN,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,Root:195216431976,development,Usage & Billing Data Lab for FinOps,finops
2515,195000000000,2026-04-14 08:00:00+00:00,2026-04-14 09:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0a5b9c01d1bbecc0b,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.690556,0.345278,RunInstances,0.007182,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,Root:195216431976,development,Usage & Billing Data Lab for FinOps,finops

<h2 style="text-align:center; 
           /* background:rgba(63, 56, 46, 0.5); */
           color:rgb(232, 140, 35); 
           font-size:35px; 
           padding:15px;
           border-radius:12px;
           display: inline-block">
     <b> Selected column name description</b>
</h2>

| Column              | Description                                                            |
| ------------------- | ---------------------------------------------------------------------- |
| account_id          | AWS account identifier.                                                |
| usage_start         | Start time of the billing usage period.                                |
| usage_end           | End time of the billing usage period.                                  |
| service             | AWS service name.                                                      |
| service_code        | AWS service code.                                                      |
| resource_id         | Unique AWS resource identifier.                                        |
| instance_type       | EC2 instance type used.                                                |
| instance_family     | EC2 instance family category.                                          |
| region              | AWS region where the resource is deployed.                             |
| usage_type          | Type of resource consumption being billed.                             |
| usage_amount        | Quantity of resource usage.                                            |
| normalized_usage    | AWS normalized usage amount used for comparison across instance sizes. |
| operation           | AWS operation that generated the cost.                                 |
| cost                | Total cost incurred for the usage record.                              |
| cost_rate           | Unit cost rate applied to the usage.                                   |
| currency            | Billing currency (e.g., USD).                                          |
| pricing_term        | Pricing model (On-Demand, Reserved, Savings Plan, etc.).               |
| operating_system    | Operating system associated with the resource.                         |
| vcpu                | Number of virtual CPUs allocated.                                      |
| memory              | Memory capacity of the resource.                                       |
| network_performance | Network performance specification.                                     |
| storage             | Storage capacity attached to the resource.                             |
| storage_class       | AWS storage class used.                                                |
| volume_type         | EBS volume type.                                                       |
| processor           | Processor family or model.                                             |
| architecture        | CPU architecture (x86, ARM, etc.).                                     |
| created_by          | Resource creator tag value.                                            |
| environment         | Environment tag (Dev, Test, QA, Prod, etc.).                           |
| project             | Project tag associated with the resource.                              |
| team                | Team or department responsible for the resource.                       |

* <b>To identify missing values and their % in each columns

In [16]:
missing_val = cleaned_data.isnull().sum()
missing_val_per = cleaned_data.isnull().sum()/len(cleaned_data) * 100

missing_data = pd.DataFrame({
    'Missing Values': missing_val,
    '% of Percentage': missing_val_per
})

missing_data

                     Missing Values  % of Percentage
account_id                        0         0.000000
usage_start                       0         0.000000
usage_end                         0         0.000000
service                           5         0.198728
service_code                      0         0.000000
resource_id                     693        27.543720
instance_type                  2500        99.364070
instance_family                2500        99.364070
region                            5         0.198728
usage_type                        0         0.000000
usage_amount                      0         0.000000
normalized_usage                  0         0.000000
operation                        93         3.696343
cost                              0         0.000000
cost_rate                       108         4.292528
currency                          0         0.000000
pricing_term                    876        34.817170
operating_system               2498        99.284579
vcpu                           2500        99.364070
memory                         2500        99.364070
network_performance            2500        99.364070
storage                        2500        99.364070
storage_class                  2462        97.853736
volume_type                    1614        64.149444
processor                      2500        99.364070
architecture                   2500        99.364070
created_by                     2295        91.216216
environment                    2505        99.562798
project                        2505        99.562798
team                           2505        99.562798

In [ ]:
# Fill missing service names only where the service_code is known
service_name_map = {
    "AmazonEC2": "Amazon Elastic Compute Cloud",
    "AmazonRDS": "Amazon Relational Database Service",
    "AmazonVPC": "Amazon Virtual Private Cloud",
}

missing_before = cleaned_data['service'].isna().sum()
service_lookup = cleaned_data['service_code'].map(service_name_map)
cleaned_data['service'] = cleaned_data['service'].fillna(service_lookup)

print(f"Missing service values before fill: {missing_before}")
print(f"Missing service values after fill: {cleaned_data['service'].isna().sum()}")

# Show the rows that were fixed
fixed_rows = cleaned_data.loc[
    cleaned_data['service_code'].isin(service_name_map.keys()) & cleaned_data['service'].notna(),
    ['account_id', 'service_code', 'service']
].drop_duplicates()

fixed_rows.head(10)

### **Observation**

---

***Why majority columns having missing values ? :(***

`lets analyze ...`

In [ ]:
cleaned_data

,account_id,usage_start,usage_end,service,service_code,resource_id,instance_type,instance_family,region,usage_type,usage_amount,normalized_usage,operation,cost,cost_rate,currency,pricing_term,operating_system,vcpu,memory,network_performance,storage,storage_class,volume_type,processor,architecture,created_by,environment,project,team
0,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,NaN,NaN,NaN,NaN,BoxUsage:t3.micro,1.000000,0.000000,RunInstances,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,NaN,NaN,NaN,NaN,CPUCredits:t3,1.000000,0.000000,T3CPUCredits,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,NaN,NaN,NaN,NaN,EBS:VolumeUsage.gp3,1.000000,0.000000,NaN,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Relational Database Service,AmazonRDS,NaN,NaN,NaN,NaN,Aurora:ServerlessV2Usage,1.000000,0.000000,CreateDBInstance:0021,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Virtual Private Cloud,AmazonVPC,NaN,NaN,NaN,NaN,USE1-PublicIPv4:InUseAddress,1.000000,0.000000,NaN,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,195000000000,2026-04-11 19:00:00+00:00,2026-04-11 20:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0d969006fcc3aa583,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.128889,0.064445,RunInstances,0.001340,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,NaN,NaN,NaN,NaN
2512,195000000000,2026-04-12 19:00:00+00:00,2026-04-12 20:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0df68563b3c5fa86f,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.575278,0.287639,RunInstances,0.005983,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,NaN,NaN,NaN,NaN
2513,195000000000,2026-04-12 20:00:00+00:00,2026-04-12 21:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0df68563b3c5fa86f,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.468889,0.234445,RunInstances,0.004876,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,NaN,NaN,NaN,NaN
2514,195000000000,2026-04-14 08:00:00+00:00,2026-04-14 09:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0a5b9c01d1bbecc0b,t3.micro,General purpose,us-east-1,EBSOptimized:t3.micro,0.690556,0.345278,Hourly,0.000000,0.0000,USD,OnDemand,NaN,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,Root:195216431976,development,Usage & Billing Data Lab for FinOps,finops
2515,195000000000,2026-04-14 08:00:00+00:00,2026-04-14 09:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0a5b9c01d1bbecc0b,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.690556,0.345278,RunInstances,0.007182,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,Root:195216431976,development,Usage & Billing Data Lab for FinOps,finops

#### ***Note*** 

`AWS Cost and Usage Report (CUR)` is a unified billing dataset that combines records from many AWS services into a single table.

Since different AWS services provide different attributes, AWS leaves non-applicable fields **empty (NaN)** instead of filling them with incorrect values.

Therefore, many missing values in CUR are expected behavior and do not indicate data corruption or poor data quality.

* #### **Example 1: Amazon S3**

Amazon S3 is an object storage service.

S3 does not have:

CPU,
Memory,
Operating System,
Instance Type,
vCPU,
Processor,
RAM

Therefore AWS cannot provide values for those columns.

Example:

**service_code	operating_system	memory	instance_type**

   AmazonS3	            NaN	          NaN	     NaN

This is correct because an S3 bucket is not a virtual machine.

* #### **Example 2: CloudWatch**

CloudWatch is a monitoring service.

CloudWatch does not run on:

EC2 instances,
CPUs,
RAM,
Storage devices

Therefore columns such as:

operating_system
memory
vcpu
storage
instance_type

remain NaN.

Example:

**service_code	memory	vcpu	operating_system**

AmazonCloudWatch	NaN	NaN	NaN

This is expected.

* #### **Example 3: AWS Lambda**

Lambda is a serverless service.

AWS manages the infrastructure.

Users do not see:

OS,
Processor,
Storage Device,
Instance Family

Therefore many infrastructure-related columns become NaN.

Example:

**service_code	operating_system	instance_type**

AWSLambda	NaN	NaN

* #### **Example 4: EBS**

Amazon EBS is block storage.

EBS has:

volume_type,
storage

But it does not have:

CPU,
RAM,
Operating System,
Processor

Therefore:

**service_code	memory	operating_system**
AmazonEBS	NaN	NaN

is normal.



* #### **Example 5: storage_class**

Only some storage services support storage classes.

Examples:

S3

Supports:

Standard
Standard-IA
Glacier
Deep Archive

Therefore storage_class may have values.

EC2

EC2 instances do not have S3 storage classes.

Therefore:

storage_class = NaN

is expected.

* #### **Example 6: operation Syatem**

Some CUR records represent:

Reserved Instance charges
Savings Plans charges
Tax records
Credits
Support fees

These billing entries are not actual operations.

Therefore:

operation = NaN

can occur.

* #### **Example 7: resource_id**

Not every AWS charge belongs to a specific resource.

Examples:

Data Transfer
CloudWatch Metrics
Tax
Support
Regional Charges

For these records AWS cannot assign:

resource_id

Therefore:

resource_id = NaN

is completely normal.

<h2 style="text-align:center; 
           /* background:rgba(63, 56, 46, 0.5); */
           color:rgb(232, 140, 35); 
           font-size:35px; 
           padding:15px;
           border-radius:12px;
           display: inline-block">
     <b> Exporting Cleaned dataset</b>
</h2>

In [19]:
cleaned_data.to_csv("../data/processed/preprocessed_cur.csv", index=False)

This cur dataset is for:

- Cost Analytics

- Cost Prediction

- Team Cost Tracking

- Resource Cost Tracking

<h2 style="text-align:center; 
           background:rgba(63, 56, 46, 0.5);
           color:rgb(232, 140, 35); 
           font-size:38px; 
           padding:15px;
           border-radius:12px;
           display: inline-block">
     <b> Usage_metrices Dataset</b>
</h2>

In [31]:
data2 = pd.read_csv(r"../data\processed\usage_metrics.csv")

In [45]:
data2.sample(2)

,timestamp,account_id,resource_id,service,region,cpu_utilization,memory_utilization,network_in_mb,network_out_mb,latency_ms,throughput,invocations,duration_ms,error_count,availability_percent,status_check_failed
1795,2026-04-06 18:00:00+00:00,1.950000e+11,demo-usman-27557,AWS Data Transfer,us-east-1,0.000002,0.000003,0.000007,0.000005,10.000001,0.000001,0,0.0,0,99.00,0
335,2026-04-14 08:00:00+00:00,1.950000e+11,finops-dataset-ur,Amazon Simple Storage Service,us-east-1,7.000000,11.000000,25.000000,18.000000,13.000000,5.000000,0,0.0,0,99.01,0

* <b>Now merging Usage_Metrices dataset with CUR dataset</b>

In [ ]:
final_df = pd.merge(
    cleaned_data,
    data2,
    on=["account_id", "resource_id", "service", "region"],
    how="right"
)

# Save final dataset
final_df.to_csv("aws_billing_usage_usman.csv", index=False)

print("Billing Shape:", cleaned_data.shape)
print("Metrics Shape:", data2.shape)
print("Final Shape:", final_df.shape)

Billing Shape: (2516, 30)
Metrics Shape: (2516, 16)
Final Shape: (521402, 42)

In [44]:
final_df.columns

Index(['account_id', 'usage_start', 'usage_end', 'service', 'service_code',
       'resource_id', 'instance_type', 'instance_family', 'region',
       'usage_type', 'usage_amount', 'normalized_usage', 'operation', 'cost',
       'cost_rate', 'currency', 'pricing_term', 'operating_system', 'vcpu',
       'memory', 'network_performance', 'storage', 'storage_class',
       'volume_type', 'processor', 'architecture', 'created_by', 'environment',
       'project', 'team', 'timestamp', 'cpu_utilization', 'memory_utilization',
       'network_in_mb', 'network_out_mb', 'latency_ms', 'throughput',
       'invocations', 'duration_ms', 'error_count', 'availability_percent',
       'status_check_failed'],
      dtype='str')

In [43]:
final_df

,account_id,usage_start,usage_end,service,service_code,resource_id,instance_type,instance_family,region,usage_type,usage_amount,normalized_usage,operation,cost,cost_rate,currency,pricing_term,operating_system,vcpu,memory,network_performance,storage,storage_class,volume_type,processor,architecture,created_by,environment,project,team,timestamp,cpu_utilization,memory_utilization,network_in_mb,network_out_mb,latency_ms,throughput,invocations,duration_ms,error_count,availability_percent,status_check_failed
0,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,NaN,NaN,NaN,NaN,BoxUsage:t3.micro,1.000000,0.000000,RunInstances,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-01 00:00:00+00:00,7.000000,11.000000,25.0000,18.000000,13.000000,5.00000,0,0.0,0,99.010000,0
1,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,NaN,NaN,NaN,NaN,CPUCredits:t3,1.000000,0.000000,T3CPUCredits,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-01 00:00:00+00:00,7.000000,11.000000,25.0000,18.000000,13.000000,5.00000,0,0.0,0,99.010000,0
2,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,NaN,NaN,NaN,NaN,EBS:VolumeUsage.gp3,1.000000,0.000000,NaN,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-01 00:00:00+00:00,7.000000,11.000000,25.0000,18.000000,13.000000,5.00000,0,0.0,0,99.010000,0
3,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,NaN,NaN,NaN,NaN,BoxUsage:t3.micro,1.000000,0.000000,RunInstances,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-01 00:00:00+00:00,7.000000,11.000000,25.0000,18.000000,13.000000,5.00000,0,0.0,0,99.010000,0
4,195000000000,2026-04-01 00:00:00+00:00,2026-05-01 00:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,NaN,NaN,NaN,NaN,CPUCredits:t3,1.000000,0.000000,T3CPUCredits,0.000000,NaN,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-01 00:00:00+00:00,7.000000,11.000000,25.0000,18.000000,13.000000,5.00000,0,0.0,0,99.010000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521397,195000000000,2026-04-14 08:00:00+00:00,2026-04-14 09:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0a5b9c01d1bbecc0b,t3.micro,General purpose,us-east-1,EBSOptimized:t3.micro,0.690556,0.345278,Hourly,0.000000,0.0000,USD,OnDemand,NaN,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,Root:195216431976,development,Usage & Billing Data Lab for FinOps,finops,2026-04-14 08:00:00+00:00,4.833892,7.596116,17.2639,12.430008,12.071668,3.45278,0,0.0,0,99.006906,0
521398,195000000000,2026-04-14 08:00:00+00:00,2026-04-14 09:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0a5b9c01d1bbecc0b,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.690556,0.345278,RunInstances,0.007182,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,Root:195216431976,development,Usage & Billing Data Lab for FinOps,finops,2026-04-14 08:00:00+00:00,4.833892,7.596116,17.2639,12.430008,12.071668,3.45278,0,0.0,0,99.006906,0
521399,195000000000,2026-04-14 08:00:00+00:00,2026-04-14 09:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0a5b9c01d1bbecc0b,NaN,NaN,us-east-1,CPUCredits:t3,0.172470,0.000000,T3CPUCredits,0.008623,0.0500,USD,OnDemand,Linux,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Root:195216431976,development,Usage & Billing Data Lab for FinOps,finops,2026-04-14 08:00:00+00:00,4.833892,7.596116,17.2639,12.430008,12.071668,3.45278,0,0.0,0,99.006906,0
521400,195000000000,2026-04-14 08:00:00+00:00,2026-04-14 09:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0a5b9c01d1bbecc0b,t3.micro,General purpose,us-east-1,EBSOptimized:t3.micro,0.690556,0.345278,Hourly,0.000000,0.0000,USD,OnDemand,NaN,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,Root:195216431976,development,Usage & Billing Data Lab for FinOps,finops,2026-04-14 08:00:00+00:00,4.833892,7.596116,17.2639,12.430008,12.071668,3.45278,0,0.0,0,99.006906,0
521401,195000000000,2026-04-14 08:00:00+00:00,2026-04-14 09:00:00+00:00,Amazon Elastic Compute Cloud,AmazonEC2,i-0a5b9c01d1bbecc0b,t3.micro,General purpose,us-east-1,BoxUsage:t3.micro,0.690556,0.345278,RunInstances,0.007182,0.0104,USD,OnDemand,Linux,2.0,1 GiB,Up to 5 Gigabit,EBS only,NaN,NaN,Intel Skylake E5 2686 v5,64-bit,Root:195216431976,development,Usage & Billing Data Lab for FinOps,finops,2026-04-14 08:00:00+00:00,4.833892,7.596116,17.2639,12.430008,12.071668,3.45278,0,0.0,0,99.006906,0

<h2 style="text-align:center; 
           /* background:rgba(63, 56, 46, 0.5); */
           color:rgb(232, 140, 35); 
           font-size:35px; 
           padding:15px;
           border-radius:12px;
           display: inline-block">
     <b> category-wise usagemetrices columns</b>
</h2>

---
This dataset contains operational and performance metrics generated for AWS resources. 

These metrics can be used for resource monitoring, cost optimization, waste detection, rightsizing recommendations, anomaly detection, and reliability analysis.

### **Resource Identification**

| Column      | Description                                                                   |
| ----------- | ----------------------------------------------------------------------------- |
| timestamp   | Time when the metric was recorded.                                            |
| account_id  | AWS account identifier.                                                       |
| resource_id | Unique AWS resource identifier (EC2 instance, Lambda function, volume, etc.). |
| service     | AWS service name associated with the resource.                                |
| region      | AWS region where the resource is deployed.                                    |


### **Compute Metrics (EC2 / ECS / EKS)**
| Column             | Description                                                          |
| ------------------ | -------------------------------------------------------------------- |
| cpu_utilization    | Average CPU utilization percentage during the measurement period.    |
| memory_utilization | Average memory utilization percentage during the measurement period. |
| network_in_mb      | Amount of inbound network traffic in MB.                             |
| network_out_mb     | Amount of outbound network traffic in MB.                            |

## **Network Metrics**
| Column     | Description                                             |
| ---------- | ------------------------------------------------------- |
| latency_ms | Average network latency in milliseconds.                |
| throughput | Data transfer throughput during the measurement period. |


### **Lambda Metrics**
| Column      | Description                                 |
| ----------- | ------------------------------------------- |
| invocations | Total number of Lambda function executions. |
| duration_ms | Average execution duration in milliseconds. |
| error_count | Number of failed Lambda executions.         |


### **Reliability Metrics**
| Column               | Description                                                                 |
| -------------------- | --------------------------------------------------------------------------- |
| availability_percent | Percentage of time the resource remained available.                         |
| status_check_failed  | Indicates whether a health/status check failure occurred (0 = No, 1 = Yes). |

This usage metrices dataset is for:

- Waste Detection

- Resource Utilization Analysis

- Operational Anomaly Detection